// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row
}

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	CreateDrama(ctx context.Context, arg CreateDramaParams) (DramaInfo, error)
	GetDramaByID(ctx context.Context, id int64) (DramaInfo, error)
	GetDramaByNo(ctx context.Context, dramaNo string) (DramaInfo, error)
	ListDramas(ctx context.Context, arg ListDramasParams) ([]DramaInfo, error)
	UpdateDrama(ctx context.Context, arg UpdateDramaParams) (DramaInfo, error)
	SoftDeleteDrama(ctx context.Context, arg SoftDeleteDramaParams) (DramaInfo, error)
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{db: tx}
}
