// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createDrama = `-- name: CreateDrama :one
INSERT INTO drama_info (
    drama_no, title, outline, cover_image, characters,
    character_relation_desc, status, task_no, create_by, update_by,
    create_at, update_at, deleted
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING *
`

const getDramaByID = `-- name: GetDramaByID :one
SELECT * FROM drama_info WHERE id = $1 AND deleted = FALSE
`

const getDramaByNo = `-- name: GetDramaByNo :one
SELECT * FROM drama_info WHERE drama_no = $1 AND deleted = FALSE
`

const listDramas = `-- name: ListDramas :many
SELECT * FROM drama_info
WHERE deleted = FALSE
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

const updateDrama = `-- name: UpdateDrama :one
UPDATE drama_info
SET
    title = COALESCE($2, title),
    outline = COALESCE($3, outline),
    cover_image = COALESCE($4, cover_image),
    characters = COALESCE($5, characters),
    character_relation_desc = COALESCE($6, character_relation_desc),
    status = COALESCE($7, status),
    task_no = COALESCE($8, task_no),
    update_by = COALESCE($9, update_by),
    update_at = $10
WHERE id = $1 AND deleted = FALSE
RETURNING *
`

const softDeleteDrama = `-- name: SoftDeleteDrama :one
UPDATE drama_info
SET deleted = TRUE, update_at = $2
WHERE id = $1 AND deleted = FALSE
RETURNING *
`

type CreateDramaParams struct {
	DramaNo               string
	Title                 string
	Outline               *string
	CoverImage            *string
	Characters            string
	CharacterRelationDesc string
	Status                *int16
	TaskNo                string
	CreateBy              string
	UpdateBy              string
	CreateAt              int64
	UpdateAt              int64
	Deleted               bool
}

type ListDramasParams struct {
	Limit  int32
	Offset int32
}

type UpdateDramaParams struct {
	ID                    int64
	Title                 *string
	Outline               *string
	CoverImage            *string
	Characters            *string
	CharacterRelationDesc *string
	Status                *int16
	TaskNo                *string
	UpdateBy              *string
	UpdateAt              int64
}

type SoftDeleteDramaParams struct {
	ID       int64
	UpdateAt int64
}

func (q *Queries) CreateDrama(ctx context.Context, arg CreateDramaParams) (DramaInfo, error) {
	row := q.db.QueryRow(ctx, createDrama,
		arg.DramaNo,
		arg.Title,
		arg.Outline,
		arg.CoverImage,
		arg.Characters,
		arg.CharacterRelationDesc,
		arg.Status,
		arg.TaskNo,
		arg.CreateBy,
		arg.UpdateBy,
		arg.CreateAt,
		arg.UpdateAt,
		arg.Deleted,
	)
	var i DramaInfo
	err := row.Scan(
		&i.ID,
		&i.DramaNo,
		&i.Title,
		&i.Outline,
		&i.CoverImage,
		&i.Characters,
		&i.CharacterRelationDesc,
		&i.Status,
		&i.TaskNo,
		&i.CreateBy,
		&i.UpdateBy,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Deleted,
	)
	return i, err
}

func (q *Queries) GetDramaByID(ctx context.Context, id int64) (DramaInfo, error) {
	row := q.db.QueryRow(ctx, getDramaByID, id)
	var i DramaInfo
	err := row.Scan(
		&i.ID,
		&i.DramaNo,
		&i.Title,
		&i.Outline,
		&i.CoverImage,
		&i.Characters,
		&i.CharacterRelationDesc,
		&i.Status,
		&i.TaskNo,
		&i.CreateBy,
		&i.UpdateBy,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Deleted,
	)
	return i, err
}

func (q *Queries) GetDramaByNo(ctx context.Context, dramaNo string) (DramaInfo, error) {
	row := q.db.QueryRow(ctx, getDramaByNo, dramaNo)
	var i DramaInfo
	err := row.Scan(
		&i.ID,
		&i.DramaNo,
		&i.Title,
		&i.Outline,
		&i.CoverImage,
		&i.Characters,
		&i.CharacterRelationDesc,
		&i.Status,
		&i.TaskNo,
		&i.CreateBy,
		&i.UpdateBy,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Deleted,
	)
	return i, err
}

func (q *Queries) ListDramas(ctx context.Context, arg ListDramasParams) ([]DramaInfo, error) {
	rows, err := q.db.Query(ctx, listDramas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DramaInfo
	for rows.Next() {
		var i DramaInfo
		if err := rows.Scan(
			&i.ID,
			&i.DramaNo,
			&i.Title,
			&i.Outline,
			&i.CoverImage,
			&i.Characters,
			&i.CharacterRelationDesc,
			&i.Status,
			&i.TaskNo,
			&i.CreateBy,
			&i.UpdateBy,
			&i.CreateAt,
			&i.UpdateAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

func (q *Queries) UpdateDrama(ctx context.Context, arg UpdateDramaParams) (DramaInfo, error) {
	row := q.db.QueryRow(ctx, updateDrama,
		arg.ID,
		arg.Title,
		arg.Outline,
		arg.CoverImage,
		arg.Characters,
		arg.CharacterRelationDesc,
		arg.Status,
		arg.TaskNo,
		arg.UpdateBy,
		arg.UpdateAt,
	)
	var i DramaInfo
	err := row.Scan(
		&i.ID,
		&i.DramaNo,
		&i.Title,
		&i.Outline,
		&i.CoverImage,
		&i.Characters,
		&i.CharacterRelationDesc,
		&i.Status,
		&i.TaskNo,
		&i.CreateBy,
		&i.UpdateBy,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Deleted,
	)
	return i, err
}

func (q *Queries) SoftDeleteDrama(ctx context.Context, arg SoftDeleteDramaParams) (DramaInfo, error) {
	row := q.db.QueryRow(ctx, softDeleteDrama, arg.ID, arg.UpdateAt)
	var i DramaInfo
	err := row.Scan(
		&i.ID,
		&i.DramaNo,
		&i.Title,
		&i.Outline,
		&i.CoverImage,
		&i.Characters,
		&i.CharacterRelationDesc,
		&i.Status,
		&i.TaskNo,
		&i.CreateBy,
		&i.UpdateBy,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Deleted,
	)
	return i, err
}
