// Code generated by sqlc. DO NOT EDIT.
// 运行 make sqlc 可重新生成（需安装 sqlc: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest）

package sqlc

import (
	"time"
)

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Phone     *string   `json:"phone"`
	Password  string    `json:"password"`
	Status    int16     `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DramaInfo struct {
	ID                    int64   `json:"id"`
	DramaNo               string  `json:"drama_no"`
	Title                 string  `json:"title"`
	Outline               *string `json:"outline"`
	CoverImage            *string `json:"cover_image"`
	Characters            string  `json:"characters"`
	CharacterRelationDesc string  `json:"character_relation_desc"`
	Status                *int16  `json:"status"`
	TaskNo                string  `json:"task_no"`
	CreateBy              string  `json:"create_by"`
	UpdateBy              string  `json:"update_by"`
	CreateAt              int64   `json:"create_at"`
	UpdateAt              int64   `json:"update_at"`
	Deleted               bool    `json:"deleted"`
}
