// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, phone, password, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, phone, password, status, created_at, updated_at
`

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, password, status, created_at, updated_at FROM users WHERE id = $1
`

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, password, status, created_at, updated_at FROM users WHERE email = $1
`

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($2, name),
    phone = COALESCE($3, phone),
    status = COALESCE($4, status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, name, email, phone, password, status, created_at, updated_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Phone    *string
	Password string
	Status   int16
}

type UpdateUserParams struct {
	ID     int64
	Name   *string
	Phone  *string
	Status *int16
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		//row.Scan(i.ID)  // 传入的是 ID 的副本，Scan 修改的是副本，不影响 i.ID。传指针，Scan 可以修改 i.ID
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
